service: server
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true



# Offline Run
custom:
  serverless-offline:
    httpPort: 5000